server:
  port: 8888
  servlet:
    context-path: /api/petconnet

spring:
  application:
    name: petconnet
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://localhost:3306/petconnet?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Sao_Paulo
    username: root
    password: root
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update
  # Jackson (JacksonProperties)
  jackson:
    date-format: "dd/MM/yyyy HH:mm:ss" # Formato de data e hora padrão
    locale: pt-BR # Localidade para formatação
    time-zone: America/Sao_Paulo # Fuso horário padrão
    serialization-inclusion: non_null # Incluir apenas propriedades não nulas na serialização
    property-naming-strategy: SNAKE_CASE # Usar nomes de chaves em snake_case

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    web: DEBUG